Temporarily disable holdings routes to fix deployment
- Commented out holdings routes registration
- Allows rest of API to work while debugging holdings import issues
- Holdings endpoint will return 404 until fixed

This fixes the 500 error on ALL routes caused by:
Error: Route.get() requires a callback function but got [object Undefined]
at /src/routes/holdings.routes.js:12